### ISSUE TITLE
Proxy Switcher crashes when changing screen resolution W10 Ent 1511 on Surface Pro4.

### ISSUE THREAD

**Issue by turbopsi** [mwiedemeyer/ProxySwitcher#12]
As per above. The app crashes when changing screen resolution. Any ideas?

Cheers.

**Comment by mwiedemeyer** [comment]
No, but maybe there is something in the log? (Proxy Switcher log.txt or EventLog)

**Comment by turbopsi** [comment]
EventLog: 
Log Name:      Application
Source:        Application Error
Date:          13/04/2016 7:53:09 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      ###############
Description:
Faulting application name: ProxySwitcher.exe, version: 3.6.1.322, time stamp: 0x4f6b956a
Faulting module name: KERNELBASE.dll, version: 10.0.10586.0, time stamp: 0x5632d1de
Exception code: 0xc000041d
Fault offset: 0x0000000000071f08
Faulting process id: 0x14d8
Faulting application start time: 0x01d195059d06045e
Faulting application path: C:\Program Files (x86)\Proxy Switcher\ProxySwitcher.exe
Faulting module path: C:\WINDOWS\system32\KERNELBASE.dll
Report Id: 72801885-d4e1-4a8a-ba4c-fd343b006b63
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-04-12T21:53:09.036489500Z" />
    <EventRecordID>2174</EventRecordID>
    <Channel>Application</Channel>
    <Computer>#############>
    <Security />
  </System>
  <EventData>
    <Data>ProxySwitcher.exe</Data>
    <Data>3.6.1.322</Data>
    <Data>4f6b956a</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.10586.0</Data>
    <Data>5632d1de</Data>
    <Data>c000041d</Data>
    <Data>0000000000071f08</Data>
    <Data>14d8</Data>
    <Data>01d195059d06045e</Data>
    <Data>C:\Program Files (x86)\Proxy Switcher\ProxySwitcher.exe</Data>
    <Data>C:\WINDOWS\system32\KERNELBASE.dll</Data>
    <Data>72801885-d4e1-4a8a-ba4c-fd343b006b63</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>  

Thanks

**Comment by turbopsi** [comment]
Version=1
EventType=APPCRASH
EventTime=131049735604835449
ReportType=2
Consent=1
UploadTime=131049735607990829
ReportIdentifier=88381b4c-00fd-11e6-90c9-b4ae2be9d389
IntegratorReportIdentifier=79905e59-ef90-46d1-a64b-58cd9f01af56
NsAppName=ProxySwitcher.exe
Response.BucketId=ea0428e73e6b84fe2e014fc0ff69cf53
Response.BucketTable=4
Response.LegacyBucketId=120351179327
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=ProxySwitcher.exe
Sig[1].Name=Application Version
Sig[1].Value=3.6.1.322
Sig[2].Name=Application Timestamp
Sig[2].Value=4f6b956a
Sig[3].Name=Fault Module Name
Sig[3].Value=KERNELBASE.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=10.0.10586.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=5632d1de
Sig[6].Name=Exception Code
Sig[6].Value=c000041d
Sig[7].Name=Exception Offset
Sig[7].Value=0000000000071f08
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.10586.2.0.0.256.4
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=3081
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=9080
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=908044c16bd1af2df975f6fee20ab85c
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=870f
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=870ff81d3a89c2915693b04a3b7a80e6
UI[2]=C:\Program Files (x86)\Proxy Switcher\ProxySwitcher.exe
UI[3]=Proxy Switcher has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files (x86)\Proxy Switcher\ProxySwitcher.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\WINDOWS\system32\KERNEL32.dll
LoadedModule[4]=C:\WINDOWS\system32\KERNELBASE.dll
LoadedModule[5]=C:\WINDOWS\system32\apphelp.dll
LoadedModule[6]=C:\WINDOWS\system32\ADVAPI32.dll
LoadedModule[7]=C:\WINDOWS\system32\msvcrt.dll
LoadedModule[8]=C:\WINDOWS\system32\sechost.dll
LoadedModule[9]=C:\WINDOWS\system32\RPCRT4.dll
LoadedModule[10]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
LoadedModule[11]=C:\WINDOWS\system32\SHLWAPI.dll
LoadedModule[12]=C:\WINDOWS\system32\combase.dll
LoadedModule[13]=C:\WINDOWS\system32\bcryptPrimitives.dll
LoadedModule[14]=C:\WINDOWS\system32\GDI32.dll
LoadedModule[15]=C:\WINDOWS\system32\USER32.dll
LoadedModule[16]=C:\WINDOWS\system32\IMM32.DLL
LoadedModule[17]=C:\WINDOWS\system32\kernel.appcore.dll
LoadedModule[18]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[19]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
LoadedModule[20]=C:\WINDOWS\SYSTEM32\MSVCR120_CLR0400.dll
LoadedModule[21]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\mscorlib\e24742a3939bece9db8105d99720b0e0\mscorlib.ni.dll
LoadedModule[22]=C:\WINDOWS\system32\ole32.dll
LoadedModule[23]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[24]=C:\Program Files\Common Files\microsoft shared\ink\tiptsf.dll
LoadedModule[25]=C:\WINDOWS\system32\OLEAUT32.dll
LoadedModule[26]=C:\WINDOWS\SYSTEM32\CRYPTSP.dll
LoadedModule[27]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[28]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[29]=C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
LoadedModule[30]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System\cb0700ff6398b8e9d0d936cfc4894ba1\System.ni.dll
LoadedModule[31]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\PresentationCore\5a7e2a9e91e0e1b45828a67f8ff1c096\PresentationCore.ni.dll
LoadedModule[32]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\Presentatio5ae0f00f#\9713d2c1ded41534c81644755cc11b07\PresentationFramework.ni.dll
LoadedModule[33]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Core\5290f26e6772518e2dd9d9c55bcc9a10\System.Core.ni.dll
LoadedModule[34]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\WindowsBase\59e9ca559f216839706cd7369886dd41\WindowsBase.ni.dll
LoadedModule[35]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Xaml\e3e372a5a0e10caa89dc8707deb2f16c\System.Xaml.ni.dll
LoadedModule[36]=C:\WINDOWS\SYSTEM32\dwrite.dll
LoadedModule[37]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\wpfgfx_v0400.dll
LoadedModule[38]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\PresentationNative_v0400.dll
LoadedModule[39]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll
LoadedModule[40]=C:\WINDOWS\system32\dwmapi.dll
LoadedModule[41]=C:\WINDOWS\system32\MSCTF.dll
LoadedModule[42]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Runt73a1fc9d#\8c85dcb027bc7a70af9690ab07754a67\System.Runtime.Remoting.ni.dll
LoadedModule[43]=C:\WINDOWS\system32\ws2_32.dll
LoadedModule[44]=C:\WINDOWS\system32\mswsock.dll
LoadedModule[45]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Configuration\7ad6bc6ee277d5eed690e8c1c9400ff7\System.Configuration.ni.dll
LoadedModule[46]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Xml\c0ce652aa04bc1fee99308a0a2ac79f8\System.Xml.ni.dll
LoadedModule[47]=C:\WINDOWS\system32\shell32.dll
LoadedModule[48]=C:\WINDOWS\system32\cfgmgr32.dll
LoadedModule[49]=C:\WINDOWS\system32\windows.storage.dll
LoadedModule[50]=C:\WINDOWS\system32\shcore.dll
LoadedModule[51]=C:\WINDOWS\system32\powrprof.dll
LoadedModule[52]=C:\WINDOWS\system32\profapi.dll
LoadedModule[53]=C:\WINDOWS\SYSTEM32\ntmarta.dll
LoadedModule[54]=C:\WINDOWS\SYSTEM32\efswrt.dll
LoadedModule[55]=C:\WINDOWS\SYSTEM32\wintypes.dll
LoadedModule[56]=C:\WINDOWS\SYSTEM32\edputil.dll
LoadedModule[57]=C:\WINDOWS\SYSTEM32\iphlpapi.dll
LoadedModule[58]=C:\WINDOWS\SYSTEM32\DNSAPI.dll
LoadedModule[59]=C:\WINDOWS\system32\NSI.dll
LoadedModule[60]=C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
LoadedModule[61]=C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
LoadedModule[62]=C:\WINDOWS\SYSTEM32\WINNSI.DLL
LoadedModule[63]=C:\WINDOWS\SYSTEM32\urlmon.dll
LoadedModule[64]=C:\WINDOWS\SYSTEM32\iertutil.dll
LoadedModule[65]=C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
LoadedModule[66]=C:\WINDOWS\SYSTEM32\d3d9.dll
LoadedModule[67]=C:\WINDOWS\SYSTEM32\igdumdim64.dll
LoadedModule[68]=C:\WINDOWS\system32\SETUPAPI.dll
LoadedModule[69]=C:\WINDOWS\SYSTEM32\mscms.dll
LoadedModule[70]=C:\WINDOWS\SYSTEM32\USERENV.dll
LoadedModule[71]=C:\WINDOWS\SYSTEM32\WindowsCodecsExt.dll
LoadedModule[72]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\Presentatioaec034ca#\c8fb282a099f5148606b8620c70cba25\PresentationFramework.Aero2.ni.dll
LoadedModule[73]=C:\WINDOWS\system32\clbcatq.dll
LoadedModule[74]=C:\WINDOWS\SYSTEM32\SspiCli.dll
LoadedModule[75]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Drawing\07904e28a4042013cf2850aa829d512c\System.Drawing.ni.dll
LoadedModule[76]=C:\WINDOWS\SYSTEM32\WtsApi32.dll
LoadedModule[77]=C:\WINDOWS\SYSTEM32\WINSTA.dll
LoadedModule[78]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\PenIMC.dll
LoadedModule[79]=C:\WINDOWS\System32\wisp.dll
LoadedModule[80]=C:\WINDOWS\SYSTEM32\atlthunk.dll
LoadedModule[81]=C:\Program Files\Common Files\Microsoft Shared\Ink\tpcps.dll
LoadedModule[82]=C:\WINDOWS\system32\dataexchange.dll
LoadedModule[83]=C:\WINDOWS\system32\d3d11.dll
LoadedModule[84]=C:\WINDOWS\system32\dcomp.dll
LoadedModule[85]=C:\WINDOWS\system32\dxgi.dll
LoadedModule[86]=C:\WINDOWS\system32\twinapi.appcore.dll
LoadedModule[87]=C:\WINDOWS\SYSTEM32\igc64.dll
LoadedModule[88]=C:\WINDOWS\SYSTEM32\wininet.dll
LoadedModule[89]=C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll
LoadedModule[90]=C:\WINDOWS\SYSTEM32\winhttp.dll
LoadedModule[91]=C:\WINDOWS\SYSTEM32\sxs.dll
LoadedModule[92]=C:\WINDOWS\system32\explorerframe.dll
LoadedModule[93]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\diasymreader.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=Proxy Switcher
AppPath=C:\Program Files (x86)\Proxy Switcher\ProxySwitcher.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=9CA4A374C777B22BB50396A173A10E37

**Comment by turbopsi** [comment]
Version=1
EventType=CLR20r3
EventTime=131049735572075502
ReportType=2
Consent=1
UploadTime=131049735577085112
ReportIdentifier=860e25d0-00fd-11e6-90c9-b4ae2be9d389
IntegratorReportIdentifier=e000dba9-81df-4950-8c6a-6b7e2192874a
NsAppName=ProxySwitcher.exe
Response.BucketId=95a700244e5ebec144d2d30bab908a8c
Response.BucketTable=5
Response.LegacyBucketId=-1409233160
Response.type=4
Sig[0].Name=Problem Signature 01
Sig[0].Value=ProxySwitcher.exe
Sig[1].Name=Problem Signature 02
Sig[1].Value=3.6.1.322
Sig[2].Name=Problem Signature 03
Sig[2].Value=4f6b956a
Sig[3].Name=Problem Signature 04
Sig[3].Value=Hardcodet.Wpf.TaskbarNotification
Sig[4].Name=Problem Signature 05
Sig[4].Value=1.0.4.0
Sig[5].Name=Problem Signature 06
Sig[5].Value=4b83c9e6
Sig[6].Name=Problem Signature 07
Sig[6].Value=a6
Sig[7].Name=Problem Signature 08
Sig[7].Value=2f
Sig[8].Name=Problem Signature 09
Sig[8].Value=System.ComponentModel.Win32
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.10586.2.0.0.256.4
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=3081
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=0666
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=0666f8d2adca2b7a70531585237be59c
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=ddcb
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=ddcb4d95b12d9881d3558244e9e5ea1f
UI[2]=C:\Program Files (x86)\Proxy Switcher\ProxySwitcher.exe
UI[3]=Proxy Switcher has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files (x86)\Proxy Switcher\ProxySwitcher.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\WINDOWS\system32\KERNEL32.dll
LoadedModule[4]=C:\WINDOWS\system32\KERNELBASE.dll
LoadedModule[5]=C:\WINDOWS\system32\apphelp.dll
LoadedModule[6]=C:\WINDOWS\system32\ADVAPI32.dll
LoadedModule[7]=C:\WINDOWS\system32\msvcrt.dll
LoadedModule[8]=C:\WINDOWS\system32\sechost.dll
LoadedModule[9]=C:\WINDOWS\system32\RPCRT4.dll
LoadedModule[10]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
LoadedModule[11]=C:\WINDOWS\system32\SHLWAPI.dll
LoadedModule[12]=C:\WINDOWS\system32\combase.dll
LoadedModule[13]=C:\WINDOWS\system32\bcryptPrimitives.dll
LoadedModule[14]=C:\WINDOWS\system32\GDI32.dll
LoadedModule[15]=C:\WINDOWS\system32\USER32.dll
LoadedModule[16]=C:\WINDOWS\system32\IMM32.DLL
LoadedModule[17]=C:\WINDOWS\system32\kernel.appcore.dll
LoadedModule[18]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[19]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
LoadedModule[20]=C:\WINDOWS\SYSTEM32\MSVCR120_CLR0400.dll
LoadedModule[21]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\mscorlib\e24742a3939bece9db8105d99720b0e0\mscorlib.ni.dll
LoadedModule[22]=C:\WINDOWS\system32\ole32.dll
LoadedModule[23]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[24]=C:\Program Files\Common Files\microsoft shared\ink\tiptsf.dll
LoadedModule[25]=C:\WINDOWS\system32\OLEAUT32.dll
LoadedModule[26]=C:\WINDOWS\SYSTEM32\CRYPTSP.dll
LoadedModule[27]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[28]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[29]=C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
LoadedModule[30]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System\cb0700ff6398b8e9d0d936cfc4894ba1\System.ni.dll
LoadedModule[31]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\PresentationCore\5a7e2a9e91e0e1b45828a67f8ff1c096\PresentationCore.ni.dll
LoadedModule[32]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\Presentatio5ae0f00f#\9713d2c1ded41534c81644755cc11b07\PresentationFramework.ni.dll
LoadedModule[33]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Core\5290f26e6772518e2dd9d9c55bcc9a10\System.Core.ni.dll
LoadedModule[34]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\WindowsBase\59e9ca559f216839706cd7369886dd41\WindowsBase.ni.dll
LoadedModule[35]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Xaml\e3e372a5a0e10caa89dc8707deb2f16c\System.Xaml.ni.dll
LoadedModule[36]=C:\WINDOWS\SYSTEM32\dwrite.dll
LoadedModule[37]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\wpfgfx_v0400.dll
LoadedModule[38]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\PresentationNative_v0400.dll
LoadedModule[39]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll
LoadedModule[40]=C:\WINDOWS\system32\dwmapi.dll
LoadedModule[41]=C:\WINDOWS\system32\MSCTF.dll
LoadedModule[42]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Runt73a1fc9d#\8c85dcb027bc7a70af9690ab07754a67\System.Runtime.Remoting.ni.dll
LoadedModule[43]=C:\WINDOWS\system32\ws2_32.dll
LoadedModule[44]=C:\WINDOWS\system32\mswsock.dll
LoadedModule[45]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Configuration\7ad6bc6ee277d5eed690e8c1c9400ff7\System.Configuration.ni.dll
LoadedModule[46]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Xml\c0ce652aa04bc1fee99308a0a2ac79f8\System.Xml.ni.dll
LoadedModule[47]=C:\WINDOWS\system32\shell32.dll
LoadedModule[48]=C:\WINDOWS\system32\cfgmgr32.dll
LoadedModule[49]=C:\WINDOWS\system32\windows.storage.dll
LoadedModule[50]=C:\WINDOWS\system32\shcore.dll
LoadedModule[51]=C:\WINDOWS\system32\powrprof.dll
LoadedModule[52]=C:\WINDOWS\system32\profapi.dll
LoadedModule[53]=C:\WINDOWS\SYSTEM32\ntmarta.dll
LoadedModule[54]=C:\WINDOWS\SYSTEM32\efswrt.dll
LoadedModule[55]=C:\WINDOWS\SYSTEM32\wintypes.dll
LoadedModule[56]=C:\WINDOWS\SYSTEM32\edputil.dll
LoadedModule[57]=C:\WINDOWS\SYSTEM32\iphlpapi.dll
LoadedModule[58]=C:\WINDOWS\SYSTEM32\DNSAPI.dll
LoadedModule[59]=C:\WINDOWS\system32\NSI.dll
LoadedModule[60]=C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
LoadedModule[61]=C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
LoadedModule[62]=C:\WINDOWS\SYSTEM32\WINNSI.DLL
LoadedModule[63]=C:\WINDOWS\SYSTEM32\urlmon.dll
LoadedModule[64]=C:\WINDOWS\SYSTEM32\iertutil.dll
LoadedModule[65]=C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
LoadedModule[66]=C:\WINDOWS\SYSTEM32\d3d9.dll
LoadedModule[67]=C:\WINDOWS\SYSTEM32\igdumdim64.dll
LoadedModule[68]=C:\WINDOWS\system32\SETUPAPI.dll
LoadedModule[69]=C:\WINDOWS\SYSTEM32\mscms.dll
LoadedModule[70]=C:\WINDOWS\SYSTEM32\USERENV.dll
LoadedModule[71]=C:\WINDOWS\SYSTEM32\WindowsCodecsExt.dll
LoadedModule[72]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\Presentatioaec034ca#\c8fb282a099f5148606b8620c70cba25\PresentationFramework.Aero2.ni.dll
LoadedModule[73]=C:\WINDOWS\system32\clbcatq.dll
LoadedModule[74]=C:\WINDOWS\SYSTEM32\SspiCli.dll
LoadedModule[75]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Drawing\07904e28a4042013cf2850aa829d512c\System.Drawing.ni.dll
LoadedModule[76]=C:\WINDOWS\SYSTEM32\WtsApi32.dll
LoadedModule[77]=C:\WINDOWS\SYSTEM32\WINSTA.dll
LoadedModule[78]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\PenIMC.dll
LoadedModule[79]=C:\WINDOWS\System32\wisp.dll
LoadedModule[80]=C:\WINDOWS\SYSTEM32\atlthunk.dll
LoadedModule[81]=C:\Program Files\Common Files\Microsoft Shared\Ink\tpcps.dll
LoadedModule[82]=C:\WINDOWS\system32\dataexchange.dll
LoadedModule[83]=C:\WINDOWS\system32\d3d11.dll
LoadedModule[84]=C:\WINDOWS\system32\dcomp.dll
LoadedModule[85]=C:\WINDOWS\system32\dxgi.dll
LoadedModule[86]=C:\WINDOWS\system32\twinapi.appcore.dll
LoadedModule[87]=C:\WINDOWS\SYSTEM32\igc64.dll
LoadedModule[88]=C:\WINDOWS\SYSTEM32\wininet.dll
LoadedModule[89]=C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll
LoadedModule[90]=C:\WINDOWS\SYSTEM32\winhttp.dll
LoadedModule[91]=C:\WINDOWS\SYSTEM32\sxs.dll
LoadedModule[92]=C:\WINDOWS\system32\explorerframe.dll
LoadedModule[93]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\diasymreader.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=Stopped working
ConsentKey=CLR20r3
AppName=Proxy Switcher
AppPath=C:\Program Files (x86)\Proxy Switcher\ProxySwitcher.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=9CA4A374C777B22BB50396A173A10E37


Thanks

**Comment by turbopsi** [comment]
@ mwiedemeyer,
Have you had a chance to go over the logs above? Cheers.

**Comment by turbopsi** [comment]
@ mwiedemeyer,
 Have you had a chance to go over the logs above? Cheers.

**Comment by mwiedemeyer** [comment]
Well, it seems to be an issue with the [TaskbarNotification control](http://www.hardcodet.net/wpf-notifyicon) I'm using. There seems to be a newer version, so maybe that one will fix it.

**Comment by turbopsi** [comment]
I'm happy to test if you have the time to update the control.

**Comment by mwiedemeyer** [comment]
It is the same issue as #10 so I close this one.

**Comment by turbopsi** [comment]
This should remain open as there's no current fix yet? Not even @ issue #10 as suggested. This software has great potential and would appreciate if the issue could be resolved.

**Comment by mwiedemeyer** [comment]
Sorry, you were right. I just fixed it. Please try the new release: https://github.com/mwiedemeyer/ProxySwitcher/releases/tag/3.6.3

**Comment by AndrewBuis** [comment]
The new version resolved the crashing issue in Windows 10 for me on a laptop. Docking/undocking/plugging in a projector or hdmi tv/closing lid all caused crashes for me.

**Comment by turbopsi** [comment]
Hi Andrew, can you please share which version your running? I'm sure I've tried the most recent version publically available. Thanks

Sent from my Windows Phone
________________________________

**Comment by turbopsi** [comment]
Just saw this post. Thank you. I will install and test early next week. Results will be posted here. Thanks.

Sent from my Windows Phone
________________________________

**Comment by AndrewBuis** [comment]
The 3.6.3 version posted above.
On Jun 10, 2016 6:44 PM, "turbopsi" <notifications@github.com> wrote:

Hi Andrew, can you please share which version your running? I'm sure I've
tried the most recent version publically available. Thanks

Sent from my Windows Phone
________________________________

**Comment by AndrewBuis** [comment]
The new version 3.6.3 was working for me. Coming into the office now, and the actions are missing from my networks, and the "Add Action" only has "Find More Actions". Uninstalling that version, and going back hasn't fixed it either.

**Comment by mwiedemeyer** [comment]
That means, that the "AddIns" subfolder is missing. The structure has to be:

- ProxySwitcher.exe

- AddIns\(...)


________________________________
Von: AndrewBuis <notifications@github.com>
Gesendet: Montag, 13. Juni 2016 13:58
An: mwiedemeyer/ProxySwitcher
Cc: Marco Wiedemeyer; State change
Betreff: Re: [mwiedemeyer/ProxySwitcher] Proxy Switcher crashes when changing screen resolution W10 Ent 1511 on Surface Pro4. (#12)


The new version 3.6.3 was working for me. Coming into the office now, and the actions are missing from my networks, and the "Add Action" only has "Find More Actions". Uninstalling that version, and going back hasn't fixed it either.

-

**Comment by AndrewBuis** [comment]
Folder is there. I extracted the zip file into the already created folder in Program Files (x86) from the previous install.

**Comment by AndrewBuis** [comment]
I also tried de-installing the new version, deleting folder in program files, then create a new folder and extracting there. It didn't help. Also tried running as administrator.

**Comment by AndrewBuis** [comment]
Looks like extracting the zip doesn't register the dlls on first run. Searching regedit, I have:
C:|Program Files (x86)|Proxy Switcher|Addins|ProxySwitcher.Actions.DefaultActions.dll
Then the entry:
ProxySwitcher.Actions.DefaultActions,Version="3.6.1.0",Culture="neutral",PublicKeyToken="C62B3978F9D76BE9",ProcessorArchitecture="MSIL"

Is there a .msi version available?

**Comment by turbopsi** [comment]
+ 1 in regards to making an .msi version available as per the original installer. Thanks

**Comment by turbopsi** [comment]
Any update on the .msi ? Thanks
