### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by aminmk** [mwiedemeyer/ProxySwitcher#19]
Can you please describe how does it work?
I can't find any tutorial

**Comment by NabiKAZ** [comment]
Any body here?!

I use latest `.exe` v3.6.3
I add new network.

But there are not any option in the `Add action` menu. Just show `Add more actions`, when clicked, open http://projects2.mwiedemeyer.de/ProxySwitcher/SitePages/MoreAddIns.aspx URL, and I get `Not Found HTTP Error 404.`
Then I try download addon from here: http://proxyswitcher.net/#addins , when I install it, get me this error: `This action addin is not compatible with the currently installed version of proxy switcher. download the latest version here: http://mwiedemeyer.de/ProxySwitcher"` and when I click on `Yes`, redirect to new URL: https://blog.mwiedemeyer.de/ProxySwitcher and get `XML Error (<Error><Code>BlobNotFound</Code>)` ...

I'm very confused !

**Comment by mwiedemeyer** [comment]
Please try to install it using the MSI from http://proxyswitcher.net and then replace the files with the contents of this zip: https://github.com/mwiedemeyer/ProxySwitcher/releases/tag/3.6.3

**Comment by NabiKAZ** [comment]
I install MSI from that link, and works 3.6.1, and show items in "add Action", but when overwrite zip file, the version was 3.6.1, but don't show any items in "add action" menu.

Now about 3.6.1, How does it work?!
