### ISSUE TITLE
Possibility to repeat checking  continuously

### ISSUE THREAD

**Issue by metalolf** [mwiedemeyer/ProxySwitcher#20]
To my shame, I have to admit, that I have to work here in a bad configured network.
Even iv the proxy setting are configured with ProxySwitcher or manually, the settings will be reset due to bad configured group policies every few minutes :(

To compile a work-around, I would like to have some information:
1. Question: what is the frequency ProxySwitcher is checking its defined triggers?
2. Question: is there a way to continuously repeat (eg. every 5 minutes) the re-checking of ProxySwitcher likewise the manual application which is possible already

Kind Regards,
Florian

**Comment by mwiedemeyer** [comment]
It is checking the network on a network change event sent from Windows.
However, you can trigger re-detect with a command line arg:
`ProxySwitcher.exe /redetect`
ProxySwitcher must be running already. A call with this argument triggers the running instance to redetect the network config.

**Comment by metalolf** [comment]
Perfect, thx!

Am 30.03.2017 um 12:27 schrieb Marco Wiedemeyer <notifications@github.com>:

Closed #20.
