### ISSUE TITLE
GPO settings - settings files are not be copied to the local client

### ISSUE THREAD

**Issue by maestro7879** [mwiedemeyer/ProxySwitcher#26]
I'm using the GPO template. If I delete the files in ...\AppData\Roaming\ProxySwitcher\V3 I assumed that either when the GPO is refreshed or proxyswitcher is restarted it would pull those locally files from the network share I configured in the GPO. That's not happened, it will pull the log file but nothing else.

**Comment by mwiedemeyer** [comment]
Hi,
yes, that is how it is supposed to work. See here: https://github.com/mwiedemeyer/ProxySwitcher/blob/2d072c1755e73af3768ca4b4143c37d7fad78816/ProxySwitcher.Core/Policy/PolicyManager.cs#L61
It copies all files from the location specified in the policy to the local directory. The user starting ProxySwitcher needs the permission to access the network share you specified.
If there is an error, you should see a message in the log. Please search for `Copy settings failed`

**Comment by maestro7879** [comment]
Thanks for the reply. I confirmed that the users do have access to the folder. 
The files will copy if I delete the Log.txt file from the location where the files are stored. This only works once as the Log.txt file is created again. I do see the Copy settings failed line in the log.

**Comment by mwiedemeyer** [comment]
Ok, so if you see the error message please post it here, so I might see what the problem is.

**Comment by maestro7879** [comment]
Solved - Interaction issue with another program.
