### ISSUE TITLE
Doesn't work with new versions of Firefox 

### ISSUE THREAD

**Issue by chicco27** [mwiedemeyer/ProxySwitcher#6]
The swicth from proxy entries does'nt work on new versions of Firefox (38 and 39 tested). Only on starting the first time work correctly, if I change network (and then proxy) it was detect by program and change correcly on Internet Explorer settings, but no changes was affected on Firefox Browser.

**Comment by mwiedemeyer** [comment]
That is not new. Firefox does not have an API to notify Firefox about settings changes from external processes. After a proxy change, you always have to restart Firefox.
