### ISSUE TITLE
Checkbox for proxy set in IE8 without proxy

### ISSUE THREAD

**Issue by rvb04** [mwiedemeyer/ProxySwitcher#7]
Hallo Entwicklerteam,
wenn kein Proxy eingegeben ist (z.B. Home-Anschluss), wird trotzdem der Haken im IE8 gesetzt (s. Snapshot im Anhang). Das führt bei manchen Anwendungen zu lästigen Fehlern.

-- 
Mit freundlichen Grüssen

Richard
![unbenannt](https://cloud.githubusercontent.com/assets/13777458/9244130/9c6e3b26-4198-11e5-8e02-6faf59569a1e.JPG)

**Comment by mwiedemeyer** [comment]
Und du hast auch "Proxy deaktivieren" als Aktion bei "Unbekanntem Netzwerk" (bzw deinem "Home" Netzwerk) konfiguriert?

**Comment by rvb04** [comment]
Nein, die Einstellung kannte ich nicht. Also war das Problem wie oft der 
Benutzer :-).

Danke für die schnelle Antwort.

VG RVB

Am 13.08.2015 um 09:28 schrieb Marco Wiedemeyer:
