### ISSUE TITLE
feature request:copy profile/action function

### ISSUE THREAD

**Issue by mgmonti** [mwiedemeyer/ProxySwitcher#9]
may be very useful have have di possibility to copy a profile to change some detail (e.g. creating a new profile for any wifi connection used). Also copy a specific action may be useful.

**Comment by Rogeriosaban** [comment]
Hello,

Anyone knows how to export/copy the user profile to be used on another computer ?

**Comment by JojoS62** [comment]
you should find the settings in 
c:\Users\userXY\AppData\Roaming\ProxySwitcher\   (for Windows 7)
just try to copy this to the other computer.

**Comment by Rogeriosaban** [comment]
Hi JojoS62

It works fine !

Thank you !!!
